### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Lantianyou** [Lunakepio/death-star-trench-run#2]
Hi Alex. I saw your tweet and demo. Totally stunned by it. My name is Tianyou Lan, I am an React dev learning `Three.js`. I have a few suggestions for this project, would you like to adopt them and assign them for me to help. If so, I would be extremely honored.

1. Use `pnpm` as dependencies management tools. It provides clearity on lock files and faster to install
2. Change titles of the `index.html` file, currently it is  `vite + React`
3. Add TypeScript, it would be a huge change, but `threejs` and `react` have solid support on types, so it would bring more benefit than cost.
4. Add renovate bot to automatically submit PR updating dependencies.

If any of the above you think is feasible, I would love to submit PR for it.

**Comment by mustache-dev** [comment]
Hello Tianyou Lan, thank you for your message! I appreciate your input. It is true that both Three.js and React have robust support for TypeScript. While I am not well-versed in TypeScript myself, I encourage you to proceed with rewriting the project in TypeScript if you are willing to do so. There is much to be gained from this in terms of learning opportunities.

I as well am unfamiliar with pnpm and its functionalities. Furthermore, I agree that there is a need to modify the titles and meta descriptions.
Will do!
